"""
Run the W3C multi-chain SLA test.

Open-loop scheduler at the configured target QPS (default 72) for the configured
duration (default 60s). Each request is generated by w3c.workload.RequestGenerator,
which round-robins across the 5 chains and picks 1-3 addresses per query.

Hard caps that prevent silent misreporting:
  * Per-request HTTP timeout == --response-time SLA (so a slow Bitquery cannot
    quietly hide as a long-tail latency — it's marked SLA-fail).
  * Concurrency cap (semaphore) == --concurrency (matches W3C's stated 42 in-flight).

This script does NOT mutate any Nomics/Tron module — Tron is fully unaffected.
"""

from __future__ import annotations

import argparse
import asyncio
import os
import sys
import time
from datetime import datetime, timezone

import aiohttp
from dotenv import load_dotenv

from utils.logging_setup import close_run_logging, setup_run_logging
from utils.unsuccessful_log import (
    close_unsuccessful_log,
    get_path as get_unsuccessful_log_path,
    log_unsuccessful,
    open_unsuccessful_log,
)
from w3c.client import W3cQueryOutcome, execute_w3c_query
from w3c.config import (
    W3cSettings,
    configure,
    defaults_from_env,
    get_settings,
    reset_settings,
)
from w3c.metrics import (
    build_report,
    categorize_failure,
    is_w3c_success,
    print_report,
)
from w3c.workload import (
    AddressBook,
    DEFAULT_W3C_POOL_PATH,
    RequestGenerator,
)

load_dotenv()

LOG_EVERY_N = max(1, int(os.getenv("W3C_LOG_EVERY_N", "1")))
PROGRESS_EVERY_N = max(1, int(os.getenv("W3C_PROGRESS_EVERY_N", "200")))


def build_arg_parser() -> argparse.ArgumentParser:
    env = defaults_from_env()
    parser = argparse.ArgumentParser(
        description=(
            "W3C SLA report — sustained-QPS multi-chain Transfers aggregation test"
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--qps", type=int, default=env.target_qps, metavar="N",
        help="Target sustained queries-per-second",
    )
    parser.add_argument(
        "--concurrency", type=int, default=env.concurrency, metavar="N",
        help="Max in-flight requests (semaphore)",
    )
    parser.add_argument(
        "--duration", type=float, default=env.duration_sec, metavar="SEC",
        help="How long to keep launching new requests (seconds)",
    )
    parser.add_argument(
        "--response-time", "--sla-response", dest="response_sec",
        type=float, default=env.max_response_sec, metavar="SEC",
        help="Max per-request response time SLA (also used as HTTP timeout)",
    )
    parser.add_argument(
        "--error-rate-threshold", dest="error_rate_pct",
        type=float, default=env.error_rate_threshold_pct, metavar="PCT",
        help="Failure-rate threshold for the warning note at end of report",
    )
    parser.add_argument(
        "--addresses-path", type=str, default=str(DEFAULT_W3C_POOL_PATH),
        metavar="PATH",
        help="Path to JSON pool of per-chain sample addresses",
    )
    parser.add_argument(
        "--chains", type=str, default=None, metavar="LIST",
        help="Comma-separated chains to include (default: all chains present in pool)",
    )
    return parser


def init_sla(argv: list[str] | None = None) -> tuple[W3cSettings, argparse.Namespace]:
    reset_settings()
    parser = build_arg_parser()
    args = parser.parse_args(argv if argv is not None else [])
    if args.qps <= 0:
        parser.error("--qps must be positive")
    if args.concurrency <= 0:
        parser.error("--concurrency must be positive")
    if args.duration <= 0:
        parser.error("--duration must be positive")
    if args.response_sec <= 0:
        parser.error("--response-time must be positive")
    settings = configure(
        target_qps=args.qps,
        concurrency=args.concurrency,
        duration_sec=args.duration,
        max_response_sec=args.response_sec,
        error_rate_threshold_pct=args.error_rate_pct,
    )
    return settings, args


def _print_section(title: str) -> None:
    line = "─" * 64
    print(f"\n{line}\n  {title}\n{line}", flush=True)


def _ts() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S.%f")[:-3] + "Z"


def _addrs_label(addresses: tuple[str, ...]) -> str:
    """Compact label for per-request logs (full list still goes to unsuccessful log)."""
    if not addresses:
        return "[]"
    if len(addresses) == 1:
        return addresses[0]
    return f"{addresses[0]} +{len(addresses) - 1}"


def _format_failure(error_detail: str | None, http_status: int, sla_sec: float) -> str:
    detail = (error_detail or "unknown error").replace("\n", " ")
    lower = detail.lower()
    if "request timeout" in lower:
        return f"WE STOPPED · TIMEOUT (>{sla_sec:g}s) — {detail}"
    if "exceeded" in lower and "sla" in lower:
        return f"WE STOPPED · SLOW (>{sla_sec:g}s SLA) — {detail}"
    if lower.startswith("http "):
        return f"SERVER ERROR · {detail}"
    if "is null" in lower:
        return f"SERVER ERROR · GraphQL null — {detail}"
    if "invalid json" in lower or "could not parse" in lower:
        return f"CLIENT ERROR · parse — {detail}"
    if http_status not in (0, 200):
        return f"SERVER ERROR · HTTP {http_status} — {detail}"
    return f"CLIENT/NETWORK ERROR — {detail}"


def _log_request_sent(req_num: int, total_expected: int, chain: str, addrs: tuple[str, ...]) -> None:
    if req_num % LOG_EVERY_N != 0 and req_num != total_expected:
        return
    w = max(4, len(str(total_expected)))
    print(
        f"  {_ts()}  [{req_num:>{w}}/{total_expected}] → sent     "
        f"{chain:<9}  {_addrs_label(addrs)}",
        flush=True,
    )


def _log_request_done(
    req_num: int,
    total_expected: int,
    *,
    outcome: W3cQueryOutcome,
    sla_sec: float,
) -> None:
    if req_num % LOG_EVERY_N != 0 and req_num != total_expected:
        return
    w = max(4, len(str(total_expected)))
    ok = is_w3c_success(outcome, sla_sec)
    mark = "✓" if ok else "✗"
    if ok:
        sums = ""
        if outcome.sending_sum_usd is not None or outcome.receiving_sum_usd is not None:
            s = outcome.sending_sum_usd or 0.0
            r = outcome.receiving_sum_usd or 0.0
            sums = f" · send=${s:,.0f}  recv=${r:,.0f}"
        status = f"{outcome.latency_ms:.0f} ms{sums}"
    else:
        status = _format_failure(outcome.error, outcome.status, sla_sec)
        if outcome.latency_ms > 0:
            status = f"{outcome.latency_ms:.0f} ms · {status}"
    print(
        f"  {_ts()}  [{req_num:>{w}}/{total_expected}] {mark} done    "
        f"{outcome.chain:<9}  {_addrs_label(outcome.addresses)}  {status}",
        flush=True,
    )


async def run_sustained_load(
    *,
    settings: W3cSettings,
    generator: RequestGenerator,
    sla_sec: float,
) -> tuple[list[W3cQueryOutcome], int, float, float, int]:
    """
    Open-loop scheduler:
      * launch a new request every 1/target_qps seconds, for `duration_sec`
      * semaphore caps concurrent in-flight at `concurrency`
      * each request is bounded by `sla_sec` (HTTP timeout = SLA)
      * waits for all in-flight to drain after the scheduling window closes

    Returns: (outcomes, scheduled_count, scheduling_wall_sec, completion_wall_sec, peak_in_flight)
    """
    target_qps = settings.target_qps
    concurrency = settings.concurrency
    duration = settings.duration_sec
    interval = 1.0 / target_qps
    expected_total = int(round(target_qps * duration))

    _print_section(
        f"Sustained load · target {target_qps} QPS · {duration:g}s · "
        f"concurrency cap {concurrency}"
    )
    print(
        f"  Per-request timeout: {sla_sec:g}s (= response-time SLA)\n"
        f"  Expected requests: ~{expected_total} ({target_qps} QPS × {duration:g}s)\n"
        f"  Chains: {', '.join(c.name for c in generator.active_chains())}\n",
        flush=True,
    )

    semaphore = asyncio.Semaphore(concurrency)
    connector = aiohttp.TCPConnector(limit=concurrency + 8)
    in_flight = 0
    peak_in_flight = 0
    outcomes: list[W3cQueryOutcome] = []
    tasks: list[asyncio.Task] = []

    async with aiohttp.ClientSession(connector=connector) as session:

        async def _run_one(req_num: int) -> W3cQueryOutcome:
            nonlocal in_flight, peak_in_flight
            request = generator.next_request()
            _log_request_sent(req_num, expected_total, request.chain.name, request.addresses)
            async with semaphore:
                in_flight += 1
                if in_flight > peak_in_flight:
                    peak_in_flight = in_flight
                try:
                    outcome = await execute_w3c_query(
                        session, request=request, timeout_sec=sla_sec,
                    )
                finally:
                    in_flight -= 1
            _log_request_done(req_num, expected_total, outcome=outcome, sla_sec=sla_sec)
            if not is_w3c_success(outcome, sla_sec):
                category = categorize_failure(outcome.error)
                log_unsuccessful(
                    req_num=req_num,
                    total=expected_total,
                    address=f"{outcome.chain}:{','.join(outcome.addresses)}",
                    category=category,
                    http_status=outcome.status,
                    latency_ms=outcome.latency_ms,
                    record_count=0,
                    expected_count=None,
                    raw_error=outcome.raw_response_body or outcome.error,
                    sla_target_sec=sla_sec,
                )
            return outcome

        scheduling_started = time.perf_counter()
        next_tick = time.monotonic()
        scheduled = 0
        while True:
            now_perf = time.perf_counter()
            if (now_perf - scheduling_started) >= duration:
                break
            now_mono = time.monotonic()
            if now_mono < next_tick:
                await asyncio.sleep(next_tick - now_mono)
            scheduled += 1
            tasks.append(asyncio.create_task(_run_one(scheduled), name=f"w3c-req-{scheduled}"))
            next_tick += interval

        scheduling_wall = time.perf_counter() - scheduling_started
        print(
            f"\n  Scheduling window closed: {scheduled} requests launched in "
            f"{scheduling_wall:.1f}s — draining in-flight responses…\n",
            flush=True,
        )

        completed = 0
        for finished in asyncio.as_completed(tasks):
            outcome = await finished
            outcomes.append(outcome)
            completed += 1
            if completed % PROGRESS_EVERY_N == 0 or completed == len(tasks):
                print(
                    f"  … {completed}/{len(tasks)} responses received "
                    f"({time.perf_counter() - scheduling_started:.0f}s elapsed)",
                    flush=True,
                )

        completion_wall = time.perf_counter() - scheduling_started

    return outcomes, scheduled, scheduling_wall, completion_wall, peak_in_flight


async def run_report(args: argparse.Namespace) -> None:
    if not os.getenv("BITQUERY_TOKEN"):
        raise SystemExit("Set BITQUERY_TOKEN in .env")
    if not os.getenv("BITQUERY_GRAPHQL_URL"):
        raise SystemExit("Set BITQUERY_GRAPHQL_URL in .env")

    settings = get_settings()
    sla_sec = settings.request_timeout_sec

    from pathlib import Path
    book = AddressBook.load(Path(args.addresses_path))
    chains_filter: list[str] | None = None
    if args.chains:
        chains_filter = [s.strip() for s in args.chains.split(",") if s.strip()]
        missing = [c for c in chains_filter if c not in book.chains_present()]
        if missing:
            raise SystemExit(
                f"Chains not in address pool: {missing}. "
                f"Available: {book.chains_present()}"
            )

    from w3c.workload import CHAINS, CHAINS_BY_NAME
    chains_to_use = (
        [CHAINS_BY_NAME[c] for c in chains_filter]
        if chains_filter
        else [c for c in CHAINS if c.name in book.chains_present()]
    )
    generator = RequestGenerator(book, chains=chains_to_use)

    print(
        f"Address pool: {book.summary()}\n"
        f"Active chains for this run: "
        f"{', '.join(c.name for c in generator.active_chains())}\n",
        flush=True,
    )

    outcomes, scheduled, sched_wall, completion_wall, peak = await run_sustained_load(
        settings=settings, generator=generator, sla_sec=sla_sec,
    )

    report = build_report(
        outcomes,
        scheduled_count=scheduled,
        scheduling_wall_sec=sched_wall,
        completion_wall_sec=completion_wall,
        peak_in_flight=peak,
        unsuccessful_log_path=get_unsuccessful_log_path(),
    )
    print_report(report)


def main(argv: list[str] | None = None) -> None:
    if argv is None:
        argv = sys.argv[1:]
    settings, args = init_sla(argv)
    log_path = setup_run_logging()
    unsuccessful_path = open_unsuccessful_log(log_path)
    print(f"Logging to terminal and file:\n  {log_path.resolve()}", flush=True)
    print(f"Unsuccessful requests log:\n  {unsuccessful_path.resolve()}\n", flush=True)
    print(
        f"W3C SLA: {settings.target_qps} QPS sustained · "
        f"concurrency {settings.concurrency} · "
        f"duration {settings.duration_sec:g}s · "
        f"{settings.max_response_sec:g}s response (timeout {settings.request_timeout_sec:g}s)\n",
        flush=True,
    )
    try:
        asyncio.run(run_report(args))
    finally:
        close_unsuccessful_log()
        close_run_logging()


if __name__ == "__main__":
    main()
